POST http://localhost:8000/api/v1/create_specializations/
Content-Type: application/json

{
    "name": "Specialization 1"
}

### Update specialization
PUT http://localhost:8000/api/v1/update_specialization/
Content-Type: application/json

{
    "id": 1,
    "name": "Specialization 2"
}

### Delete specialization
DELETE http://localhost:8000/api/v1/delete_specialization/
Content-Type: application/json

{
    "id": 1
}
###

GET http://localhost:8000/api/v1/get_specializations/

###
POST http://localhost:8000/api/v1/create_group
Content-Type: application/json

{
    "group_name": "group 1",
    "id_specialization": 1
}

###
GET http://localhost:8000/api/v1/get_schedules

### Get 
GET http://localhost:8000/api/v1/get_students_by_group_id
Content-Type: application/json

{
    "id_group": 1
}

###
GET http://localhost:8000/api/v1/get_students_by_group_id?id_group=1

###
GET http://localhost:8000/api/v1/get_students

### 
POST http://localhost:8000/api/v1/get_schedule_id
Content-Type: application/json

{
    "date": "2024-12-28",
    "lesson_number": 1
}

### 
POST http://localhost:8000/api/v1/get_students_by_group_id
Content-Type: application/json

{
    "id_group": 2
}