POST http://localhost:8000/api/v1/create_specializations/
Content-Type: application/json

{
    "name": "Specialization 1"
}

### Update specialization
PUT http://localhost:8000/api/v1/update_specialization/
Content-Type: application/json

{
    "id": 1,
    "name": "Specialization 2"
}

### Delete specialization
DELETE http://localhost:8000/api/v1/delete_specialization/
Content-Type: application/json

{
    "id": 1
}
###

GET http://localhost:8000/api/v1/get_specializations/

###
POST http://localhost:8000/api/v1/create_group
Content-Type: application/json

{
    "group_name": "group 1",
    "id_specialization": 1
}

###
GET http://localhost:8000/api/v1/get_schedules